<?php
$ACT_REGISTER = '001';
$ACT_LOGIN = '002';
$ACT_FORGOT_PASSWORD = '003';

$ACT_LOGIN_FOLLOW_UP = '503';
$ACT_RESEND_EMAIL = '531';
$ACT_LOGOUT = '535';
$ACT_POST_SEND_GUILD = '536';
$ACT_WHISPER = '537';
$ACT_CHANGE_FACE = '801';
$ACT_DELETE_ACCOUNT = '802';
$ACT_CHANGE_NAME = '803';
$ACT_CHANGE_EMAIL = '804';
$ACT_CHANGE_PASS = '805';

$ACT_HERO = '004';
$ACT_MAIL = '005';

$ACT_HALL_OF_FAME = '007';

$ACT_DUNGEON_ENTER = '008';
$ACT_DUNGEON_FIGHT = '519';

$ACT_SETTINGS = '009';

$ACT_TAVERN_ENTER = '010';
$ACT_ARENA_ENTER = '011';
$ACT_ARENA_FIGHT = '512';
$ACT_WORK_ENTER = '012';
$ACT_WORK_START = '502';
$ACT_WORK_CANCEL = '505';

$ACT_QUEST_START = '510';
$ACT_QUEST_CANCEL = '511';
$ACT_QUEST_SKIP = '189';

$ACT_ENTER_SHOP_SHAKES = '013';
$ACT_ENTER_SHOP_FIDGET = '014';

$ACT_STALL_ENTER = '015';
$ACT_STALL_BUY = '020';
$ACT_BUY_MOUNT_10 = '0201';
$ACT_BUY_MOUNT_20 = '0202';
$ACT_BUY_MOUNT_30 = '0203';
$ACT_BUY_MOUNT_50 = '0204';

$ACT_BUY_STAT = '021';

$ACT_MUSHDEALER_ENTER = '016';
$ACT_SCREEN_GILDE_GRUENDEN = '017';

$ACT_GAMBLE = '022';
$ACT_VIEW_GUILD = '023';
$ACT_GUILD_RANKING = '024';
$ACT_DEALER_AKTION = '025';
$ACT_DEALER_SPONSOR = '026';
$ACT_KILL_POTION = '027';

$ACT_GUILD_CREATE = '101';
$ACT_GUILD_ENTER = '006';
$ACT_GUILD_DELETE = '102';
$ACT_GUILD_INVITE = '103';
$ACT_GUILD_EXPEL = '104';
$ACT_GUILD_SET_MASTER = '105';
$ACT_GUILD_SET_OFFICER = '106';
$ACT_GUILD_IMPROVE = '107';
$ACT_GUILD_SET_DESC = '108';
$ACT_GUILD_RENAME = '109';
$ACT_GUILD_JOIN = '110';
$ACT_GUILD_DONATE = '111';
$ACT_GUILD_JOIN_ATTACK = '112';
$ACT_GUILD_JOIN_DEFENSE = '113';
$ACT_GUILD_COMMENCE_ATTACK = '114';
$ACT_GUILD_INVITE_PLAYER = '115';
$ACT_GUILD_INVITE_PLAYER = '115';
$ACT_GUILD_ATT = '112%3B';
$ACT_GUILD_DEF = '113%3B';

$ACT_ALBUM = '116';

$ACT_BUY_LUXURY = '195';
$ACT_LOAD_CATAPULT = '196';


$ACT_TOILET_FLUSH = '302';
$ACT_SCREEN_TOILET = '303';
$ACT_SCREEN_TOWER = '312';
$ACT_TOWER_TRY = '313';
$ACT_COPYCAT_BOOST = '314';
$ACT_MOVE_COPYCAT_ITEM = '318';
$ACT_SCREEN_WITCH = '322';
$ACT_WITCH_DONATE = '323';
$ACT_WITCH_ENCHANT = '325';
$ACT_REQUEST_GUILD_NAMES = '533';
$ACT_REWATCH_BATTLE = '356';


$ACT_USE_ITEM = '504';

$ACT_REROLL_ITEMS = '506';
$ACT_MAIL_READ = '507';
$ACT_MAIL_DELETE = '508';
$ACT_MAIL_SEND = '509';

$ACT_VIEW_OTHER_PLAYER = '513';
$ACT_HERO_DESC = '514';
$ACT_SEND_CHAT = '516';
$ACT_GET_CHAT_HISTORY = '517';
$ACT_DRINK_BEER = '518';



//	PLAYER INDEX
$INDEX_PLAYER_PAYMENT_ID = 0;
$INDEX_PLAYER_ID = 1;
$INDEX_PLAYER_LAST_ONLINE = 2;
$INDEX_PLAYER_REGISTRATION_DATE = 3;
$INDEX_PLAYER_REGISTRATION_IP = 4;
$INDEX_PLAYER_MSG_COUNT = 5;
$INDEX_PLAYER_VALIDATION_IP = 6;
$INDEX_PLAYER_LEVEL = 7;
$INDEX_PLAYER_EXP = 8;
$INDEX_PLAYER_EXP_NEXT = 9;
$INDEX_PLAYER_HONOR = 10;
$INDEX_PLAYER_RANK = 11;
$INDEX_PLAYER_CLASS_RANK = 12;
$INDEX_PLAYER_SILVER = 13;
$INDEX_PLAYER_MUSH = 14;
$INDEX_PLAYER_MUSH_GAINED = 15;
$INDEX_PLAYER_MUSH_SPEND = 16;

$INDEX_PLAYER_FACE = 17;

$INDEX_PLAYER_RACE = 27;
$INDEX_PLAYER_SEX = 28;
$INDEX_PLAYER_CLASS = 29;

$INDEX_PLAYER_ATTR_STR = 30;
$INDEX_PLAYER_ATTR_DEX = 31;
$INDEX_PLAYER_ATTR_INT = 32;
$INDEX_PLAYER_ATTR_WIT = 33;
$INDEX_PLAYER_ATTR_LUCK = 34;

$INDEX_PLAYER_ATTR_STR_ITEMS = 35;
$INDEX_PLAYER_ATTR_DEX_ITEMS = 36;
$INDEX_PLAYER_ATTR_INT_ITEMS = 37;
$INDEX_PLAYER_ATTR_WIT_ITEMS = 38;
$INDEX_PLAYER_ATTR_LUCK_ITEMS = 39;

$INDEX_PLAYER_ATTR_STR_BUY = 40;
$INDEX_PLAYER_ATTR_DEX_BUY = 41;
$INDEX_PLAYER_ATTR_INT_BUY = 42;
$INDEX_PLAYER_ATTR_WIT_BUY = 43;
$INDEX_PLAYER_ATTR_LUCK_BUY = 44;

$INDEX_PLAYER_STATUS = 45; // 2 quest 1work 0none
$INDEX_PLAYER_STATUS_EXTRA = 46;
$INDEX_PLAYER_STATUS_END = 47;

$INDEX_PLAYER_ITEM_SLOT_1 = 48;
$INDEX_PLAYER_ITEM_SLOT_2 = 60;
$INDEX_PLAYER_ITEM_SLOT_3 = 72;
$INDEX_PLAYER_ITEM_SLOT_4 = 84;
$INDEX_PLAYER_ITEM_SLOT_5 = 96;
$INDEX_PLAYER_ITEM_SLOT_6 = 108;
$INDEX_PLAYER_ITEM_SLOT_7 = 120;
$INDEX_PLAYER_ITEM_SLOT_8 = 132;
$INDEX_PLAYER_ITEM_SLOT_9 = 144;
$INDEX_PLAYER_ITEM_SLOT_10 = 156;
$INDEX_PLAYER_ITEM_SLOT_11 = 168;
$INDEX_PLAYER_ITEM_SLOT_12 = 180;
$INDEX_PLAYER_ITEM_SLOT_13 = 192;
$INDEX_PLAYER_ITEM_SLOT_14 = 204;
$INDEX_PLAYER_ITEM_SLOT_15 = 216;

$INDEX_PLAYER_QUEST_OFFER_LEVEL_1 = 229;
$INDEX_PLAYER_QUEST_OFFER_LEVEL_2 = 230;
$INDEX_PLAYER_QUEST_OFFER_LEVEL_3 = 231;

$INDEX_PLAYER_QUEST_OFFER_TYPE_1 = 232;
$INDEX_PLAYER_QUEST_OFFER_TYPE_2 = 233;
$INDEX_PLAYER_QUEST_OFFER_TYPE_3 = 234;

$INDEX_PLAYER_QUEST_OFFER_ENEMY_1 = 235;
$INDEX_PLAYER_QUEST_OFFER_ENEMY_2 = 236;
$INDEX_PLAYER_QUEST_OFFER_ENEMY_3 = 237;

$INDEX_PLAYER_QUEST_OFFER_LOCATION_1 = 238;
$INDEX_PLAYER_QUEST_OFFER_LOCATION_2 = 239;
$INDEX_PLAYER_QUEST_OFFER_LOCATION_3 = 240;

$INDEX_PLAYER_QUEST_DURATION_1 = 241;
$INDEX_PLAYER_QUEST_DURATION_2 = 242;
$INDEX_PLAYER_QUEST_DURATION_3 = 243;

$INDEX_PLAYER_QUEST_ITEM_1 = 244;
$INDEX_PLAYER_QUEST_ITEM_2 = 256;
$INDEX_PLAYER_QUEST_ITEM_3 = 268;

$INDEX_PLAYER_QUEST_EXP_1 = 280;
$INDEX_PLAYER_QUEST_EXP_2 = 281;
$INDEX_PLAYER_QUEST_EXP_3 = 282;

$INDEX_PLAYER_QUEST_SILVER_1 = 283;
$INDEX_PLAYER_QUEST_SILVER_2 = 284;
$INDEX_PLAYER_QUEST_SILVER_3 = 285;

$INDEX_PLAYER_MOUNT_ID = 286;

$INDEX_PLAYER_SHAKES_ITEM_SLOT_1 = 288; //12 attr * 6 slots
$INDEX_PLAYER_SHAKES_ITEM_SLOT_2 = 300;
$INDEX_PLAYER_SHAKES_ITEM_SLOT_3 = 312;
$INDEX_PLAYER_SHAKES_ITEM_SLOT_4 = 324;
$INDEX_PLAYER_SHAKES_ITEM_SLOT_5 = 336;
$INDEX_PLAYER_SHAKES_ITEM_SLOT_6 = 348;

$INDEX_PLAYER_FIDGET_ITEM_SLOT_1 = 361; //12 attr * 6 slots
$INDEX_PLAYER_FIDGET_ITEM_SLOT_2 = 373;
$INDEX_PLAYER_FIDGET_ITEM_SLOT_3 = 385;
$INDEX_PLAYER_FIDGET_ITEM_SLOT_4 = 397;
$INDEX_PLAYER_FIDGET_ITEM_SLOT_5 = 409;
$INDEX_PLAYER_FIDGET_ITEM_SLOT_6 = 421;

$INDEX_PLAYER_GUILD_ATTACK_TIME = 365;
$INDEX_PLAYER_GUILD_DEFEND_TIME = 367;
$INDEX_PLAYER_MSG_UNREADED = 434;
$INDEX_PLAYER_GUILD_MSG = 435;
$INDEX_PLAYER_GUILD_RANK = 436;
$INDEX_PLAYER_MUSHROOMS_MAY_DONATE = 437;
$INDEX_PLAYER_ALBUM = 438;

$INDEX_PLAYER_GUILD_JOIN_DATE = 443;
$INDEX_PLAYER_NEW_FLAGS = 444;
$INDEX_PLAYER_WE_MISS_YOU = 446;
$INDEX_PLAYER_ARMOR = 447;

$INDEX_PLAYER_DMG_MIN = 448;
$INDEX_PLAYER_DMG_MAX = 449;
$INDEX_PLAYER_LIFE = 450;
$INDEX_PLAYER_MOUNT_DURATION = 451;
$INDEX_PLAYER_TRANSACTION_COUNT = 452;
$INDEX_PLAYER_EVASION = 453;
$INDEX_PLAYER_MAGICRSISTANCE = 454;
$INDEX_PLAYER_THIRST = 456;
$INDEX_PLAYER_BEERS = 457;
$INDEX_PLAYER_DUNGEON_DONE = 458; // max 100
$INDEX_PLAYER_DUNGEON_TIME = 459;
$INDEX_PLAYER_ARENA_TIME = 460;
$INDEX_PLAYER_GUILD_EXP_BONUS = 461;
$INDEX_PLAYER_GUILD_GOLD_BONUS = 462;
$INDEX_PLAYER_EMAIL_CONFIRMED = 463;
$INDEX_PLAYER_ORDER_LVL = 465;
$INDEX_PLAYER_ORDER_DUNG = 466;
$INDEX_PLAYER_ORDER_ARENA = 467;
$INDEX_PLAYER_ORDER_QUEST = 468;
$INDEX_PLAYER_ORDER_WORK_HOURS = 469;
$INDEX_PLAYER_ORDER_WORK_GOLD = 470;
$INDEX_PLAYER_ORDER_HONOR = 471;
$INDEX_PLAYER_ORDER_MUSH = 472;
$INDEX_PLAYER_LOCKDURATION = 475;
$INDEX_PLAYER_MUSH_BOUGHT_SINCE_LAST_LOGIN = 445;
$INDEX_PLAYER_FOO = 476;
$INDEX_PLAYER_BAR = 477;
$INDEX_PLAYER_HELLO = 478;
$INDEX_PLAYER_FIRST_PAYMENT = 479;

$INDEX_PLAYER_DUNGEON_1 = 480;
$INDEX_PLAYER_DUNGEON_2 = 481;
$INDEX_PLAYER_DUNGEON_3 = 482;
$INDEX_PLAYER_DUNGEON_4 = 483;
$INDEX_PLAYER_DUNGEON_5 = 484;
$INDEX_PLAYER_DUNGEON_6 = 485;
$INDEX_PLAYER_DUNGEON_7 = 486;
$INDEX_PLAYER_DUNGEON_8 = 487;
$INDEX_PLAYER_DUNGEON_9 = 488;
$INDEX_PLAYER_DUNGEON_10 = 489;

$INDEX_PLAYER_DUNGEON_11 = 441;
$INDEX_PLAYER_DUNGEON_12 = 442;

$INDEX_PLAYER_DUNGEON_13 = 490;
$INDEX_PLAYER_TOILET = 491;
$INDEX_PLAYER_PHP_SESSION = 492;

$INDEX_PLAYER_POTION_TYPE = 493;
$INDEX_PLAYER_POTION_TIME = 496;
$INDEX_PLAYER_POTION_VALUE = 499;

$INDEX_PLAYER_POWER_LIFE_POTION = 502;
$INDEX_PLAYER_LAST_LOGIN_IP = 503;
$INDEX_PLAYER_MUSHROOM_BOUGHT_AMOUNT = 506;
$INDEX_PLAYER_GUILD_WAR_STATUS = 508;
$INDEX_PLAYER_TIME = 510;
$INDEX_PLAYER_SSID = 511;
$INDEX_PLAYER_TOWER_LEVEL = 513;


$ITEM_TYPE_WEAPON_ID = 1;
$ITEM_TYPE_SHIELD_ID = 2;
$ITEM_TYPE_ARMOR_ID = 3;
$ITEM_TYPE_BOOTS_ID = 4;
$ITEM_TYPE_GLOVES_ID = 5;
$ITEM_TYPE_HELMET_ID = 6;
$ITEM_TYPE_BELT_ID = 7;
$ITEM_TYPE_NECK_ID = 8;
$ITEM_TYPE_RING_ID = 9;
$ITEM_TYPE_AMULET_ID = 10;

$ITEM_TYPE_KEY_ID = 11;
$ITEM_TYPE_MIRROR_ID = 11;

$ITEM_TYPE_POTION_ID = 12;
$ITEM_TYPE_KLASER_ID = 13;


//	ITEM INDEX
$ITEM_TYPE_INDEX = 0;
$ITEM_ID_INDEX = 1;
$ITEM_DMG_MIN_INDEX = 2;
$ITEM_DMG_MAX_INDEX = 3;
$ITEM_ATTR_INDEX = 4;//3
$ITEM_ATTR_VAL_INDEX = 7;//3
$ITEM_GOLD_INDEX = 10;
$ITEM_MUSH_INDEX = 11;
$ITEM_ENCHANT_POWER_INDEX = 601;
$ITEM_SOCKET_POWER_INDEX = 602;

// ITEM ATTR TYPE ID
$ATTR_STR_ID = 1;
$ATTR_INT_ID = 3;
$ATTR_DEX_ID = 2;
$ATTR_WIT_ID = 4;
$ATTR_LUCK_ID = 5;
$ATTR_ALL_ID = 6;

$ITEM_POT_AGI = 12;
$ITEM_POT_STR = 11;
$ITEM_POT_INT = 13;
$ITEM_POT_WIT = 14;
$ITEM_POT_LUCK = 15;
$ITEM_POT_HP = 16;


$ERR_NAME_EXISTS = 'E001';
$ERR_NAME_LENGHT = 'E002';
$ERR_PASSWORD_TOO_SHORT = 'E003';
$ERR_EMAIL_REJECTED = 'E004';
$ERR_NAME_REJECTED = 'E005';
$ERR_LOGIN_FAILED = 'E006';
$ERR_GOLD = 'E007';
$ERR_WRONG_PASSWORD = 'E008';
$ERR_FACE_DATA_INCORRECT = 'E009';
$ERR_EMAIL_WRONG = 'E010';
$ERR_GENDER_OR_RACE = 'E011';
$ERR_EMAIL_EXISTS = 'E012';
$ERR_ALREADY_IN_GUILD = 'E013';
$ERR_NO_INDEX_FREE = 'E014';
$ERR_FIGHT_SELF = 'E015';
$ERR_GUILD_NOT_FOUND = 'E016';
$ERR_GUILD_NOT_ALLOWED = 'E017';
$ERR_GUILD_LACK_MUSH = 'E018';
$ERR_GUILD_LACK_GOLD = 'E019';
$ERR_GUILD_BUILDING_NOT_FOUND = 'E020';
$ERR_GUILD_BUILDING_MAX = 'E021';
$ERR_GUILD_NOT_MEMBER = 'E022';
$ERR_GUILD_MASTER_CANT_BE_OFFICER = 'E023';
$ERR_GUILD_IS_FULL = 'E024';
$ERR_GUILD_ALREADY_YOU_OTHER = 'E025';
$ERR_GUILD_NOT_REAL_MEMBER = 'E026';
$ERR_GUILD_ALREADY_YOU_THIS = 'E027';
$ERR_GUILD_PLAYER_NOT_FOUND = 'E028';
$ERR_SUBJECT_TOO_SHORT = 'E029';
$ERR_GUILD_TOO_EXPENSIVE = 'E030';
$ERR_GUILD_CHAT_NOT_MEMBER = 'E031';
$ERR_GUILD_CHAT_HISTORY = 'E032';
$ERR_GUILD_CHAT_TEXT_ERROR = 'E033';
$ERR_BEER = 'E034';
$ERR_BOOST = 'E042';
$ERR_GUILD_NAME_REJECTED = 'E043';
$ERR_GUILD_NAME_LENGTH = 'E044';
$ERR_GUILD_NAME_CHARACTERS = 'E045';
$ERR_GUILD_EMAIL_VALIDATE = 'E046';
$ERR_GUILD_MUSH_FREE = 'E047';
$ERR_ATTACK_AGAIN = 'E048';
$ERR_REQUEST_PW = 'E049';
$ERR_VALIDATE = 'E050';
$ERR_NO_MUSH_BAR = 'E035';
$ERR_NO_ENDURANCE = 'E036';
$ERR_WORSE_MOUNT = 'E037';
$ERR_GUILD_ALREADY_MEMBER = 'E038';
$ERR_NOT_INVITED = 'E039';
$ERR_NO_MUSH_PVP = 'E040';
$ERR_NO_MUSH_MQ = 'E041';
$ERR_GUILD_DONATE_NEG = 'E051';
$ERR_GUILD_DONATE_FRA = 'E052';
$ERR_PLAYER_DESC = 'E053';//$ERR_LOCKED_PAYMENT = 'E053'; //linijka 375 sfgame_pl.txt // 559	Twoje konto zostało zablokowane w związku z płatnościami. W razie pytań, skontaktuj się z obsługą gry za pomocą przycisku powyżej. 
$ERR_LOCKED_ADMIN = 'E054';
$ERR_TOO_SOON = 'E055';
$ERR_ACCOUNTS_PER_IP = 'E056';
$ERR_PLACE_BET = 'E057';
$ERR_INVENTORY_FULL = 'E058';
$ERR_GUILD_GOLD = 'E060';
$ERR_GUILD_ALREADY_UNDER_ATTACK = 'E061';
$ERR_GUILD_ATTACK_DELAY = 'E062';
$ERR_GUILD_ALREADY_ATTACKING = 'E063';
$ERR_GUILD_ATTACK_STATUS = 'E064';
$ERR_SESSION_EXPIRED = 'E065';
$ERR_STOP_TUNNELING = 'E066';
$ERR_REVOLT_FAILED = 'E067';
$ERR_JOINED_TOO_RECENTLY = 'E068';
$ERR_SERVER_DOWN = 'E069';
$ERR_MSG_LEVEL_TOO_LOW = 'E084';
$ERR_MSG_NOT_VALIDATED = 'E085';
$ERR_INVENTORY_FULL_ADV = 'E086';
$ERR_INVITE_NOT_VALIDATED = 'E090';
$ERR_INVITE_TOO_MANY = 'E091';
$ERR_INVITE_EMAIL_REJECTED = 'E092';
$ERR_NO_ALBUM = 'E093';
$ERR_LUXURY_ALREADY = 'E094';
$ERR_GUILD_RANK_WRONG = 'E095';
$ERR_NO_CHAT_INFO = 'E096';
$ERR_NO_CHAT_OVERFLOW = 'E097';
$ERR_TOWER_CLOSED = 'E098';
$ERR_TOWER_ITEMMOVE = 'E100';
$ERR_TOWER_NO_COPYCATS = 'E101';
$ERR_TEXT_TOO_LONG = 'E102'; //ERR_GUILD_DESCR_TOO_LONG:* = -102; // 9531 sfgame_pl.txt
$ERR_NO_SLOT_FOR_FLUSHING = 'E307';
$ERR_TOILET_EMPTY = 'E310';
$ERR_ITEM_TOILET = '357';
$ERR_FIGHT_PLAYER = 'E311';
$ERR_MSG_NO_SUCH_NAME = '204';
$ERR_DEALER_SPONSOR = '177';
$ERR_INBOX_FULL = '203';
$ERR_RECIPIENT_NOT_FOUND = '204';
$ERR_RECIPIENT_SELF = '205';
$ERR_DEALER_AKTION = '175';
$ERR_UNKNOWN = 'E999';

$RESP_ACCOUNT_SUCCESS = 1;
$RESP_LOGIN_SUCCESS = 2;
$RESP_INVITE_SUCCESS = 191;
$RESP_FAME_LIST = 3;
$RESP_SCREEN_BUILDCHAR = 4;
$RESP_SCREEN_WITCH = 324;
$RESP_GUILD_DATA = 101;
$RESP_SAVEGAME_STAY = 102;

$RESP_WORK_END = 103;
$RESP_WORK_START = 104;
$RESP_WORK_STOP = 105;
$RESP_QUEST_DONE = 106;
$RESP_QUEST_START = 107;
$RESP_QUEST_STOP = 108;
$RESP_DUNGEON_FIGHT = 122;

$RESP_PLAYER_DESC_SUCCESS = 109;
$RESP_PLAYER_SCREEN = 111;

$RESP_PLAYER_NOT_FOUND = 112;
$RESP_ATTACK_NOT_EXIST = 114;

$RESP_DEMO_SCREEN = 113;

$RESP_CHANGE_FACE_OK = 115;
$RESP_CHANGE_PASS_OK = 116;
$RESP_CHANGE_NAME_OK = 117;
$RESP_CHANGE_EMAIL_OK = 118;
$RESP_DELETE_ACCOUNT_OK = 119;

$RESP_NO_LOGIN = 120;
$RESP_REQUEST_GUILD = 121;
$RESP_GUILD_FOUND_SUCCESS = 150;
$RESP_GUILD_DELETE_SUCCESS = 151;
$RESP_GUILD_RENAME_SUCCESS = 152;
$RESP_GUILD_CHANGE_DESC_SUCCESS = 153;
$RESP_GUILD_IMPROVE_SUCCESS = 154;
$RESP_GUILD_OFFICER_SUCCESS = 155;
$RESP_GUILD_EXPEL_SUCCESS = 156;
$RESP_GUILD_INVITE_SUCCESS = 157;
$RESP_GUILD_JOIN_SUCCESS = 158;
$RESP_GUILD_MASTER_SUCCESS = 159;
$RESP_GUILD_DONATE_SUCCESS = 160;
$RESP_CHAT_HISTORY = 161;
$RESP_CHAT_LINE = 162;
$RESP_TRANS_COUNT = 163;
$RESP_EMAIL_RESENT = 164;
$RESP_PASSWORD_SENT = 165;
$RESP_VALIDATE_OK = 166;
$RESP_UPDATE_CHECK = 167;
$RESP_BET_WON = 168;
$RESP_BET_LOST = 169;
$RESP_SCREEN_GILDENHALLE = 170;
$RESP_OTHER_GUILD = 172;
$RESP_SAVEGAME_STAY_ERROR = 173;
$RESP_DEALER_AKTION = 174;
$RESP_DEALER_SPONSOR = 176;
$RESP_GUILD_FIGHT = 178;
$RESP_GUILD_JOIN_ATTACK_OK = 179;
$RESP_GUILD_JOIN_DEFENSE_OK = 180;
$RESP_GUILD_COMMENCE_ATTACK_OK = 181;
$RESP_GUILD_NAMES = 183;
$RESP_LOGIN_SUCCESS_BOUGHT = 184;
$RESP_REQUEST_GUILD_QUIET = 186;
$RESP_LOGOUT_SUCCESS = 187;
$RESP_QUEST_DONE_PIXEL = 188;
$RESP_WHISPER_SUCCESS = 190;
$RESP_INVITE_SUCCESS = 191;
$RESP_ALBUM = 192;
$RESP_QUEST_SKIP_ALLOWED = 193;
$RESP_QUEST_SKIP_ALLOWED_START = 194;
$RESP_TOILET_LOCKED = 304;
$RESP_TOILET_DROPPED = 305;
$RESP_TOILET_FULL = 306;
$RESP_TOILET_FLUSHED = 308;
$RESP_TOILET_UNLOCKED = 309;
$RESP_TOILET_TANKFULL = 311;
$RESP_TOWER_SAVE = 315;
$RESP_SAVEGAME_SHARD = 316;
$RESP_SAVEGAME_MIRROR = 317;
$RESP_MOVE_TOWER_ITEM = 319;
$RESP_TOWER_FIGHT = 321;
$RESP_TOWER_LEVEL_HELPER_BUY = 322;
$RESP_READ_MESSAGE = 201;
$RESP_MESSAGE_SENT = 202;


$SERVER_TIME = (new DateTime())->getTimestamp();
$SERVER_TIME_TOMORROW = strtotime('tomorrow');
$SERVER_TIME_HOURS = Date('H:i', Time());

$EVENT_EXP_ID = 1;
$EVENT_EPIC_ID = 2;
$EVENT_GOLD_ID = 3;
$EVENT_MUSH_ID = 4;
$EVENT_ALL_ID = 5;

$EVENT_SPECIAL_CHRISMAS = 1;
$EVENT_SPECIAL_EASTER = 2;
$EVENT_SPECIAL_HALLOWEEN = 3;
$EVENT_SPECIAL_NEWITEM = 4;

$STATUS_QUEST = 2;
$STATUS_WORK = 1;
$STATUS_IDLE = 0;

$GUILD_LEADER = 2;
$GUILD_OFFICER = 1;
$GUILD_MEMBER = 0;

$RACE_HUMAN_ID = 1;
$RACE_ELF_ID = 2;
$RACE_DWARF_ID = 3;
$RACE_GNOME_ID = 4;
$RACE_ORC_ID = 5;
$RACE_DARK_ELF_ID = 6;
$RACE_GOBLIN_ID = 7;
$RACE_DEMON_ID = 8;

$SEX_MALE = 1;
$SEX_FEMALE = 2;

$CLASS_WARRIOR_ID = 1;
$CLASS_MAGE_ID = 2;
$CLASS_SCOUT_ID = 3;

$MOUNT_10_ID = 1;
$MOUNT_20_ID = 2;
$MOUNT_30_ID = 3;
$MOUNT_50_ID = 4;

$SHOP_SHAKES_ID = 2;
$SHOP_FIDGET_ID = 1;

$MOVE_NORMAL_ID = 0;
$MOVE_SHIELD_ID = 1;
$MOVE_DODGE_ID = 2;
$MOVE_CRITIC_ID = 3;

$STATUS_QUEST_ID = 2;
$STATUS_WORK_ID = 1;
$STATUS_NONE_ID = 0;

$ORDER_LVL_ID = 1;
$ORDER_DUNG_ID = 2;
$ORDER_PVP_ID = 3;
$ORDER_QUEST_ID = 4;
$ORDER_HOURS_ID = 5;
$ORDER_GOLD_ID = 6;
$ORDER_HONOR_ID = 7;
$ORDER_FRIEND_ID = 8;

$CLIENT_IP = $_SERVER['REMOTE_ADDR'];

$monsters = array(
    'darkrider' => array('faceid' => 101, 'classid' => 1, 'weaponid' => 26, 'shieldid' => 0),
    'alien' => array('faceid' => 98, 'classid' => 3, 'weaponid' => -1, 'shieldid' => 0),
    'dragonofmadness' => array('faceid' => 146, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),
    'dragonofcold' => array('faceid' => 147, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),
    'dragonofhell' => array('faceid' => 148, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),
    'giandragon' => array('faceid' => 149, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),
    'saurus' => array('faceid' => 150, 'classid' => 3, 'weaponid' => 9, 'shieldid' => 0),
    
    
    'golem' => array('faceid' => 4, 'classid' => 1, 'weaponid' => -1),
    
    
    
    
    'banshee' => array('faceid' => 74, 'classid' => 3, 'weaponid' => -2, 'shieldid' => 0),
    
    'fire' => array('faceid' => 102, 'classid' => 3, 'weaponid' => -2, 'shieldid' => 0),
    
    'hotn' => array('faceid' => 117, 'classid' => 1, 'weaponid' => 29, 'shieldid' => 0),
    
    'graydragon' => array('faceid' => 138, 'classid' => 3, 'weaponid' => -1, 'shieldid' => 0),
    
    'dragonofdarkness' => array('faceid' => 158, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),


    'blackskullwarrior' => array('faceid' => 159, 'classid' => 1, 'weaponid' => 13, 'shieldid' => 64, 'shieldblock' => 70),



    'toxicdragon' => array('faceid' => 160, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),
    'swampdragon' => array('faceid' => 161, 'classid' => 1, 'weaponid' => -1, 'shieldid' => 0),
    
    'killingmachine' => array('faceid' => 164, 'classid' => 3, 'weaponid' => 51, 'shieldid' => 0),
    'knightoftheblackskull' => array('faceid' => 165, 'classid' => 1, 'weaponid' => 27, 'shieldid' => 0),
    'toxicgremlin' => array('faceid' => 167, 'classid' => 3, 'weaponid' => -1, 'shieldid' => 0),
    'volcano' => array('faceid' => 168, 'classid' => 1, 'weaponid' => -6, 'shieldid' => 0),
);

// Maksymalne części wyglądu dla mężczyzn
$MAX_PARTS_MALE = [
    [7, 7, 9, 6, 5, 11, 4, 13, 17, 0],  // Human
    [8, 5, 8, 7, 4, 9, 3, 7, 13, 0],   // Elf
    [8, 5, 5, 5, 5, 9, 5, 5, 13, 0],   // Dwarf
    [9, 9, 10, 6, 6, 11, 5, 12, 17, 0], // Gnome
    [6, 5, 7, 5, 5, 10, 5, 5, 9, 0],    // Orc
    [5, 5, 6, 5, 5, 8, 3, 6, 12, 0],    // Dark Elf
    [9, 6, 6, 5, 5, 12, 0, 8, 12, 0],   // Goblin
    [7, 5, 9, 6, 5, 11, 5, 10, 17, 0],  // Demon
];

// Maksymalne części wyglądu dla kobiet
$MAX_PARTS_FEMALE = [
    [6, 6, 8, 6, 6, 8, 4, 0, 5, 0],     // Human
    [7, 8, 8, 8, 7, 8, 4, 0, 5, 0],     // Elf
    [6, 8, 9, 6, 4, 8, 4, 0, 4, 0],     // Dwarf
    [6, 6, 7, 7, 6, 8, 4, 0, 5, 0],     // Gnome
    [6, 5, 7, 5, 4, 7, 4, 0, 7, 0],     // Orc
    [6, 6, 9, 6, 3, 6, 3, 0, 5, 0],     // Dark Elf
    [6, 5, 9, 5, 3, 7, 4, 0, 4, 0],     // Goblin
    [6, 5, 8, 7, 4, 7, 3, 0, 5, 0],     // Demon
];